server:
  port: 888
  
spring:  
  datasource:
      url: jdbc:mysql://3.134.84.41:3306/datahash_sale_system?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: datahash
      password: Datahash838datahash838)
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
           
  resources:
    static-locations: classpath:/static,classpath:/public,classpath:/resources,file:/home/ubuntu/backend_service/upload  
    
mybatis:
  type-aliases-package: com.springboot.dao
  configuration:
    map-underscore-to-camel-case: true
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations:
    - classpath:mybatis/*.xml  

  